<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: serif;
            margin: 20px;
            line-height: 1.4;
            font-size: 12px;
            color: #000;
        }
        
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #000;
            padding-bottom: 15px;
        }
        
        .title {
            font-size: 18px;
            font-weight: bold;
            margin: 10px 0;
        }
        
        .subtitle {
            font-size: 11px;
            color: #666;
        }
        
        .section {
            margin-bottom: 25px;
        }
        
        .section h3 {
            color: #000;
            border-bottom: 1px solid #ccc;
            padding-bottom: 3px;
            margin-bottom: 10px;
            font-size: 14px;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 15px;
        }
        
        th, td {
            border: 1px solid #000;
            padding: 6px;
            text-align: left;
            font-size: 10px;
        }
        
        th {
            background-color: #f0f0f0;
            font-weight: bold;
        }
        
        .summary-box {
            border: 1px solid #000;
            padding: 10px;
            margin-bottom: 20px;
            text-align: center;
        }
        
        .summary-item {
            margin: 5px 0;
        }
        
        .summary-number {
            font-size: 16px;
            font-weight: bold;
        }
        
        .summary-label {
            font-size: 10px;
        }
        
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 9px;
            border-top: 1px solid #000;
            padding-top: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="title">{{ $title }}</div>
        <div class="subtitle">Generated on: {{ $generatedDate }}</div>
    </div>

    <!-- Summary Section -->
    <div class="section">
        <div class="summary-box">
            <div class="summary-item">
                <div class="summary-number">{{ number_format($currentYearUsers) }}</div>
                <div class="summary-label">Users This Year ({{ $currentYear }})</div>
            </div>
            <div class="summary-item">
                <div class="summary-number">{{ number_format($totalUsers) }}</div>
                <div class="summary-label">Total Users</div>
            </div>
        </div>
    </div>

    <!-- Yearly Summary -->
    <div class="section">
        <h3>Yearly User Registration Summary</h3>
        <table>
            <thead>
                <tr>
                    <th>Year</th>
                    <th>New Users</th>
                </tr>
            </thead>
            <tbody>
                @if($usersByYear && $usersByYear->count() > 0)
                    @foreach($usersByYear as $yearData)
                        <tr>
                            <td>{{ $yearData->year ?? 'N/A' }}</td>
                            <td>{{ number_format($yearData->count ?? 0) }}</td>
                        </tr>
                    @endforeach
                @else
                    <tr>
                        <td colspan="2">No data available</td>
                    </tr>
                @endif
            </tbody>
        </table>
    </div>

    <!-- Monthly Data for Current Year -->
    <div class="section">
        <h3>Monthly User Registration for {{ $currentYear }}</h3>
        <table>
            <thead>
                <tr>
                    <th>Month</th>
                    <th>New Users</th>
                </tr>
            </thead>
            <tbody>
                @if($monthlyData && $monthlyData->count() > 0)
                    @foreach($monthlyData as $monthData)
                        <tr>
                            <td>{{ $monthData['month_name'] ?? 'Unknown' }}</td>
                            <td>{{ number_format($monthData['count'] ?? 0) }}</td>
                        </tr>
                    @endforeach
                @else
                    <tr>
                        <td colspan="2">No monthly data available</td>
                    </tr>
                @endif
            </tbody>
        </table>
    </div>

    <div class="footer">
        <p>Report generated by Bidan System</p>
        <p>© {{ date('Y') }} - All rights reserved</p>
    </div>
</body>
</html>